### PR TITLE
[FAB-17362] Reorganize `regression` Directory and Rename Tests

### PR DESCRIPTION
**Pull request by lindluni**
This change renames the regression directory to `systemtest` and moves each of the tests into a bucket according to the type of test they are performing as well as gives the scenario a name more indicative of what the test is performing

Signed-off-by: Brett Logan <brett.t.logan@ibm.com>

### CODE REVIEW

**Review by dongmingh — DISMISSED** [review]

**Comment by ryjones** [comment]
@btl5037 ready to merge?

**Comment by lindluni** [comment]
> @btl5037 ready to merge?

Blocked by #162, the surface area for that change is much wider, I'd like to rebase this one on top of that, instead of the other way around

**Review by suryalnvs — COMMENTED** [review]
FYI https://github.com/hyperledger/fabric-test/blob/b743524cf8ef382d5f1ff441277ebcd817fc7bb8/regression/upgrade/upgrade2.1.sh has to be moved to systemtest/functional/upgrade/

**Comment by lindluni** [comment]
I will keep rebasing this, there are some upcoming changes I want to pick up

**Pull request closed without merging**
