### PR TITLE
Add Basic Azure Pipeline for Chaintool

### PR DESCRIPTION
**Pull request by lindluni**
All code needs to have some level of CI performed against it, to be checked in. Ideally this will contain linting and syntax checking in the future, but just getting you guys started with it so we can get the repo configured properly and give you guys merge permission

### CODE REVIEW

**Comment by lindluni** [comment]
Once someone approves, I will merge

**Review by dongmingh — COMMENTED** [review]
looks good to me

**Comment by lindluni** [comment]
@mbwhite @awjh-ibm 

This is a basic template for you guys to get started with, for now it will just run `npm install` so we can get a successful pass on CI for merging purposes. If one of you approves this change, I will merge, and then we can add the `mergify` bot so you guys can merge your own code in the future

**Comment by awjh-ibm** [comment]
The yml LGTM, should it have run on this PR? I can only see it as waiting for status to be reported?

**Comment by lindluni** [comment]
No. It won't run until I setup the pipeline which I can't do till the YAML is merged. I just need you to approve the code and I can do the rest

**Review by awjh-ibm — APPROVED** [review]
LGTM

**Pull request merged**
