### PR TITLE
rewrite PTE using high level fabric-sdk-node.

### PR DESCRIPTION
**Pull request by dongmingh**
This PR supports the following:
connection profile generated from operator
invoke and query functions
filtered block event
transctions result report
service discovery
constant mode transactions with frequency and deviation frequency
multi-threads transactions

Signed-off-by: Dongming Hwang <dongming@ibm.com>

### CODE REVIEW

**Comment by lindluni** [comment]
Please replace all `var` declarations with `let` which is the standard now

**Comment by lindluni** [comment]
Please replace concatenations with interpolation, i.e., something like `let name = 'test' + id;` should be ``let name = `test${id}`;``

**Comment by lindluni** [comment]
In general can we revisit variable names. They need to be more descriptive to what they are, for example `txCfgPtr` is not very descriptive of what this variable is.

**Comment by lindluni** [comment]
Can we use the `yargs` package to actually implements flags. So instead of using `process.argv` we use `yargs` to name the flags and get their values. It needs to be clear what we expect the users input to be, and the `yargs` package allows you to add descriptions so people can understand what the flags expect

**Comment by dongmingh** [comment]
> Please replace concatenations with interpolation, i.e., something like `let name = 'test' + id;` should be `` let name = `test${id}`; ``

Agree

**Comment by lindluni** [comment]
In general, can we add comments to the start of functions explaining what their input parameters are, for example:

```
/**
 * Sends a predetermined number of transactions a certain frequency
 *
 * @param {string} contract The smart contract name
 * @param {number} ntx The number of transactions to send
 * @param {number} freqCB The frequency at which to send transactions
 * @returns {Promise<void>}
 */
async function execQuery(contract, ntx, freqCB) {
```

It's hard in Node.js to understand input and output since there is no typing. This will help people understand what the inputs and outputs are.

**Comment by lindluni** [comment]
While going through and adding comments, can we rethink variable names in general. A variable name should be self-describing. Abbreviations should only be used in places where it is explicitly obvious what something means.

**Comment by scottz64** [comment]
> In general can we revisit variable names. They need to be more descriptive to what they are, for example `txCfgPtr` is not very descriptive of what this variable is.

Ha. I thought that one, an abbreviation for transactionConfigurationPointer, was one of the good ones. I agree more clarity with variable names is always a good thing, although on rare occasions excessive length can get in the way of code readability.

**Pull request closed without merging**
