### PR TITLE
[Main] Update node (and npm) to latest release

### PR DESCRIPTION
**Pull request by davidkel**
Should address compile issues around node-sdk interop testing

Signed-off-by: D <d_kelsey@uk.ibm.com>

### CODE REVIEW

**Comment by denyeart** [comment]
Thanks @davidkel !

I think we'll also need it at https://github.com/hyperledger/fabric-test/blob/main/ci/azure-pipelines-interop.yml#L34

**Comment by davidkel** [comment]
@denyeart Well spotted, sorry I missed that one as it was declared differently to the other files I have updated

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.4

**Comment by denyeart** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
