### PR TITLE
Porting code from master branch

### PR DESCRIPTION
**Pull request by bharadwajambati95**

### CODE REVIEW

**Review by dongmingh — COMMENTED** [review]
1. any reason to test no TLS scenarios?  If this is just because of existing testcases, then we may need to reconsider if there is any value to test no TLS.
2. there are duplication of utility functions, such as movePTEReportFile() and GetTestStatusFromReportFile() etc.  Consider to consolidate all utility func into a common place for all regression folders to use.

**Comment by scottz64** [comment]
@dongmingh  :  my 2 cents:

1.  There are no UT or IT tests for no-TLS, and it got broken not long ago and we caught it with our no-TLS tests in our interop tests (behave). It is not critical, but testing the no-TLS helps ensure code coverage. Of course, if fabric team ever says it is no longer supported and no longer an option for beginners to test with no-TLS, then we would delete it.
2.  Maybe I missed the duplication of functions in master branch; if that is true then that could be addressed in master branch later. Since this is a port to 1.4, I would suggest merge as is. This should probably be one of the last updates needed in 1.4, and if it works then don't touch it much anymore.

**Comment by scottz64** [comment]
It is very difficult to inspect many updates in one PR, @bharadwajambati95 , even for those who inspected the originals.

1. Were there any difficulties, conflicts, or sections requiring closer scrutiny?
2. What testing was done?

**Comment by bharadwajambati95** [comment]
For the second one, we need a new package to be added under the regression folder if we want to reuse them. If it's fine to create a separate folder only for those utils under regression, then we can add them.

**Comment by dongmingh** [comment]
> @dongmingh : my 2 cents:
> 
> 1. There are no UT or IT tests for no-TLS, and it got broken not long ago and we caught it with our no-TLS tests in our interop tests (behave). It is not critical, but testing the no-TLS helps ensure code coverage. Of course, if fabric team ever says it is no longer supported and no longer an option for beginners to test with no-TLS, then we would delete it.
> 2. Maybe I missed the duplication of functions in master branch; if that is true then that could be addressed in master branch later. Since this is a port to 1.4, I would suggest merge as is. This should probably be one of the last updates needed in 1.4, and if it works then don't touch it much anymore.

@scottz64 Thanks for clarification.

**Comment by bharadwajambati95** [comment]
> It is very difficult to inspect many updates in one PR, @bharadwajambati95 , even for those who inspected the originals.
> 
> 1. Were there any difficulties, conflicts, or sections requiring closer scrutiny?
> 2. What testing was done?

@scottz64  I didn't find any difficulties. I ran the system test with this PR.

**Review by scottz64 — APPROVED** [review]

**Pull request merged**
