### PR TITLE
FAB-17295 Update pre-setup script

### PR DESCRIPTION
**Pull request by rameshthoomu**
This patch update pre-setup script to pull thirdparty images from it's source
instead of pulling it from the fabric-baseimages.

Signed-off-by: rameshthoomu <rameshbabu.thoomu@gmail.com>

### CODE REVIEW

**Comment by scottz64** [comment]
Seems this is failing in CI.
Also, @btl5037  should see this too.

**Comment by lindluni** [comment]
While it LGTM, I think I may know why it is failing, I'll need to pull the change and test locally and see if it is related to something I had to change when we made this move in Fabric Core

**Comment by scottz64** [comment]
What did you find out @btl5037 ?

**Comment by rameshthoomu** [comment]
I see Kafka containers are exiting with the below error. I am not sure how this is working in fabric. @btl5037 ^^

===> Configuring ...
KAFKA_ADVERTISED_LISTENERS is required.
Command [/usr/local/bin/dub ensure KAFKA_ADVERTISED_LISTENERS] FAILED !

**Comment by lindluni** [comment]
So I can't for the life of me figure out how this ever worked, even in our fabric integration tests when using `fabric-kafka` we set this environment variable, I just looked at the code. The Kafka doc says this is a required parameter. I'll play around with this and figure out what the right setting is

**Comment by lindluni** [comment]
Doesn't apply anymore, this code path will be removed soon in favor of the operator directly pulling its image deps

**Pull request closed without merging**
