### PR TITLE
Introduce chaincode-integration testing tool

### PR DESCRIPTION
**Pull request by awjh-ibm**
Initial drop for working towards the resolution of epic [FAB-17382](https://jira.hyperledger.org/browse/FAB-17382)

Includes work on the following tasks of the epic:
- [FAB-17383](https://jira.hyperledger.org/browse/FAB-17383) add capacity to work against multiple networks
- [FAB-17384](https://jira.hyperledger.org/browse/FAB-17384) add logging-level param and setup winston
- [FAB-17385](https://jira.hyperledger.org/browse/FAB-17385) add step defs for channel setup
- [FAB-17386](https://jira.hyperledger.org/browse/FAB-17386) add step defs for chaincode using v2 network (install + instantiate)
- [FAB-17387](https://jira.hyperledger.org/browse/FAB-17387) add tag param and tag each feature uniquely
- [FAB-17389](https://jira.hyperledger.org/browse/FAB-17389) add basic-checks feature
- [FAB-17390](https://jira.hyperledger.org/browse/FAB-17390) add advanced-types feature
- [FAB-17391](https://jira.hyperledger.org/browse/FAB-17391) add commercial-paper feature
- [FAB-17395](https://jira.hyperledger.org/browse/FAB-17395) add docs/schemas folder and defs for basic, advance and commercial paper chaincode and tool for converting to md

### CODE REVIEW

**Comment by lindluni** [comment]
Can you add a CODEOWNERS entry for the maintainers of this tool:

`/tools/chaincode-integration @awjh-ibm`

We can also add an explicit ignore on this directory to the current CI pipeline so it doesn't trigger fabric-test CI and then you can add your own CI if you need to

**Comment by awjh-ibm** [comment]
How do I configure the CI to ignore this folder as that sounds a good idea? Is it something I need to do or is that configured elsewhere?

**Comment by lindluni** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#paths

**Comment by lindluni** [comment]
You will need to add the excludes pattern from that link to the `ci/azure-pipelines.yml` file. Also you need to rebase on CODEOWNERS, a PR was just merged to update it

**Comment by btl5037** [comment]
I think you'll need to switch to the full syntax:

```trigger:
  branches:
    include:
      - master
    paths:
      exclude:
        - tools/chaincode-integration/*```

**Comment by lindluni** [comment]
I think you need to switch to the full syntax:
```
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - tools/chaincode-integration/*
pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - tools/chaincode-integration/*
```

**Comment by lindluni** [comment]
I had bad indentation, I edited to correct the indentation if you got to it before I fixed it

**Comment by mbwhite** [comment]
Thanks for working on this @awjh-ibm; looking forward to get the chaincodes tested!

**Comment by lindluni** [comment]
Are you ready to merge this @awjh-ibm

**Comment by awjh-ibm** [comment]
Happy for this to be merged

**Review by lindluni — APPROVED** [review]

**Pull request merged**
