### PR TITLE
FAB-17214 Update Azure yml files

### PR DESCRIPTION
**Pull request by rameshthoomu**
This patch removes the python installation steps from azure yml files
and updates the script section.

### CODE REVIEW

**Comment by rameshthoomu** [comment]
@suryalnvs please review..

**Comment by suryalnvs** [comment]
@rameshthoomu I am good with the changes. But smoke test with operator is failed at BeforeSuite while pulling the images from nexus.

**Comment by lindluni** [comment]
Should this still point to 1.4.4-stable images, they are starting to age out of nexus since 1.4.5 is out

**Review by suryalnvs — APPROVED** [review]

**Review by scottz64 — APPROVED** [review]
LGTM. Seems you have conflicts to resolve before merging, though.

**Pull request merged**
