### PR TITLE
Preliminary InterOp Lite Pipeline

### PR DESCRIPTION
**Pull request by lindluni**
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>

### CODE REVIEW

**Comment by lindluni** [comment]
Most of what's contained in this pipeline will pushed out into common scripts, so don't take this pipeline as a canonical implementation

**Comment by lindluni** [comment]
Waiting on CA to convert to modules: https://github.com/hyperledger/fabric-ca/pull/157

**Comment by lindluni** [comment]
Successful results here: https://dev.azure.com/Hyperledger/Fabric-Test/_build/results?buildId=14692&view=results.

A second PR on top of this will remove redundant artifacts after this is merged

**Comment by lindluni** [comment]
Testing one more time here: https://dev.azure.com/Hyperledger/Fabric-Test/_build/results?buildId=14697&view=results

**Comment by scottz64** [comment]
Why does it report SUCCESS for the Integration tests even though there are errors? https://dev.azure.com/Hyperledger/Fabric-Test/_build/results?buildId=14692&view=logs&j=8e671fb0-2618-5094-37cc-902caf839e7f&t=8d81586b-9131-54eb-476e-43d53e3e5da4

**Comment by lindluni** [comment]
> Why does it report SUCCESS for the Integration tests even though there are errors? https://dev.azure.com/Hyperledger/Fabric-Test/_build/results?buildId=14692&view=logs&j=8e671fb0-2618-5094-37cc-902caf839e7f&t=8d81586b-9131-54eb-476e-43d53e3e5da4

Ugh, because it would appear the Node project does properly report failures, regardless of whether it fails or not the `rush` targets returns a 0 exit code 😢 

Nice catch Scott, I will need to address the issue in their repo

**Comment by lindluni** [comment]
And now that I'm over there, rush always returns a zero-exit code, they publish their results from mocha so Azure can decide if the pipeline failed or not, I will need to do the same

**Comment by lindluni** [comment]
Was able to address the issue, I was building the chaincode-node modules and docker images, which was leaving behind the node-modules directories before I tarballed it. Then when I extracted it, the node-modules weren't computing properly against the rush tool chaincode uses. Waiting on test results with this change.

Thanks again Scott for finding this!

**Comment by lindluni** [comment]
Here is a new run with a successful run of chaincode node: https://dev.azure.com/Hyperledger/Fabric-Test/_build/results?buildId=14718&view=logs&j=8e671fb0-2618-5094-37cc-902caf839e7f&t=8d81586b-9131-54eb-476e-43d53e3e5da4

**Review by suryalnvs — COMMENTED** [review]
I am good with the changes but cloning fabric-test repository is moved out of install_deps.yml to the individual job definition and copied same in all jobs. Is there a reason for moving out to job definition?

**Review by suryalnvs — APPROVED** [review]
Discussed and good with the changes.

**Pull request merged**
